# k8s/deployment-demo.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-nginx
  labels:
    app: nginx-server
spec:
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx-server
        image: nginx:1.25.2
        volumeMounts:
          - name: nginx-configmap-vol
            mountPath: /etc/nginx/conf.d/default.conf
      volumes:
        - name: nginx-configmap-vol
          configMap:
            name: nginx-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://flask-app:9090;
      }
    }

---
# k8s/service-demo.yaml

apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  selector:
    app: nginx-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# k8s/deployment-demo.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-flask
  labels:
    app: flask-server
spec:
  selector:
    matchLabels:
      app: flask-server
  template:
    metadata:
        labels:
          app: flask-server
    spec:
      containers:
      - name: flask-server
        image: orrmb/flask_migrate_2k8s
        ports:
          - containerPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-mongo
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-persistent-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-storage
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi